// lib/screens/product/offer_management.dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:lucide_icons/lucide_icons.dart';
import '../../models/offer_model.dart';
import '../../models/order_model.dart';
import '../../providers/offer_provider.dart';
import '../../providers/auth_provider.dart';
import '../../providers/order_provider.dart';
import 'widgets/offer_card.dart';
import 'widgets/counter_offer_dialog.dart';
import 'order_tracking_screen.dart';

class OffersScreen extends StatefulWidget {
  const OffersScreen({super.key});

  @override
  State<OffersScreen> createState() => _OffersScreenState();
}

class _OffersScreenState extends State<OffersScreen>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);

    // Load offers when screen initializes
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _loadOffers();
    });
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  Future<void> _loadOffers() async {
    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    final offerProvider = Provider.of<OfferProvider>(context, listen: false);

    if (authProvider.user?.uid != null) {
      print('Loading offers for user: ${authProvider.user!.uid}'); // Debug log
      await offerProvider.loadUserOffers(authProvider.user!.uid);
    } else {
      print('No authenticated user found'); // Debug log
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please login to view your offers'),
          backgroundColor: Colors.red,
        ),
      );
    }
  }

  Future<void> _refreshOffers() async {
    await _loadOffers();
  }

  Future<void> _handleOfferAction(OfferModel offer, String action) async {
    final offerProvider = Provider.of<OfferProvider>(context, listen: false);
    bool success = false;

    switch (action) {
      case 'accept':
        success = await offerProvider.acceptOffer(offer.id);
        if (success) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Offer accepted successfully!'),
              backgroundColor: Colors.green,
            ),
          );
          // Create order when offer is accepted
          await _createOrderFromOffer(offer);
        }
        break;

      case 'reject':
        success = await _showRejectDialog(offer);
        break;

      case 'counter':
        success = await _showCounterOfferDialog(offer);
        break;

      case 'delete':
        success = await _showDeleteDialog(offer);
        break;

      case 'track_order':
        await _navigateToOrderTracking(offer);
        break;
    }

    if (!success && offerProvider.errorMessage != null) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(offerProvider.errorMessage!),
          backgroundColor: Colors.red,
        ),
      );
    }
  }

  Future<void> _createOrderFromOffer(OfferModel offer) async {
    try {
      final authProvider = Provider.of<AuthProvider>(context, listen: false);
      final orderProvider = Provider.of<OrderProvider>(context, listen: false);

      final order = OrderModel(
        id: '', // Will be generated by Firestore
        productId: offer.productId,
        productTitle: offer.productTitle,
        productImageUrl: offer.productImageUrl,
        productPrice: offer.offerAmount, // Use accepted offer price
        buyerId: offer.buyerId,
        buyerName: offer.buyerName,
        buyerPhone: '', // You might want to get this from user profile
        sellerId: offer.sellerId,
        sellerName: offer.sellerName,
        sellerPhone: '', // You might want to get this from user profile
        status: OrderStatus.pending,
        shippingMethod: ShippingMethod.courier,
        deliveryAddress: '', // You might want to collect this during payment
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        paymentMethod: 'Pending',
      );

      await orderProvider.createOrder(order);

      // Update offer to mark as order created
      await Provider.of<OfferProvider>(context, listen: false)
          .updateOfferOrderStatus(offer.id, true);

    } catch (e) {
      print('Error creating order: $e');
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error creating order: $e'),
          backgroundColor: Colors.red,
        ),
      );
    }
  }

  Future<void> _navigateToOrderTracking(OfferModel offer) async {
    // Find the associated order
    final orderProvider = Provider.of<OrderProvider>(context, listen: false);
    await orderProvider.loadUserOrders(offer.buyerId);

    final order = orderProvider.orders.firstWhere(
          (o) => o.productId == offer.productId &&
          o.buyerId == offer.buyerId &&
          o.sellerId == offer.sellerId,
      orElse: () => throw Exception('Order not found'),
    );

    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => OrderTrackingScreen(order: order),
      ),
    );
  }

  Future<bool> _showDeleteDialog(OfferModel offer) async {
    bool? result = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: Row(
          children: [
            Icon(LucideIcons.trash2, color: Colors.red[600], size: 20),
            const SizedBox(width: 8),
            const Text('Delete Offer'),
          ],
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Are you sure you want to delete this offer?',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 12),
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: Colors.grey[50],
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: Colors.grey[200]!),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    offer.productTitle,
                    style: const TextStyle(fontWeight: FontWeight.w500),
                    maxLines: 2,
                    overflow: TextOverflow.ellipsis,
                  ),
                  const SizedBox(height: 4),
                  Text(
                    'Offer: ₹${offer.offerAmount.toStringAsFixed(0)}',
                    style: const TextStyle(
                      color: Color(0xFF078893),
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  Text(
                    'Status: ${offer.statusDisplayName}',
                    style: TextStyle(
                      color: Colors.grey[600],
                      fontSize: 12,
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 12),
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: Colors.red[50],
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: Colors.red[200]!),
              ),
              child: Row(
                children: [
                  Icon(LucideIcons.alertTriangle,
                      color: Colors.red[600], size: 16),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      'This action cannot be undone.',
                      style: TextStyle(
                        color: Colors.red[700],
                        fontSize: 12,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(false),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            onPressed: () async {
              final offerProvider = Provider.of<OfferProvider>(
                context,
                listen: false,
              );
              final success = await offerProvider.deleteOffer(offer.id);
              Navigator.of(context).pop(success);

              if (success) {
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(
                    content: Text('Offer deleted successfully'),
                    backgroundColor: Colors.green,
                  ),
                );
              }
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.red,
              foregroundColor: Colors.white,
            ),
            child: const Text('Delete'),
          ),
        ],
      ),
    );

    return result ?? false;
  }

  Future<bool> _showRejectDialog(OfferModel offer) async {
    final TextEditingController reasonController = TextEditingController();
    bool? result = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Reject Offer'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Are you sure you want to reject the offer of ₹${offer.offerAmount.toStringAsFixed(0)}?',
            ),
            const SizedBox(height: 16),
            TextField(
              controller: reasonController,
              maxLines: 3,
              decoration: const InputDecoration(
                labelText: 'Reason (Optional)',
                border: OutlineInputBorder(),
                hintText: 'Let the buyer know why you rejected the offer...',
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(false),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () async {
              final offerProvider = Provider.of<OfferProvider>(
                context,
                listen: false,
              );
              final success = await offerProvider.rejectOffer(
                offer.id,
                reason: reasonController.text.trim().isEmpty
                    ? null
                    : reasonController.text.trim(),
              );
              Navigator.of(context).pop(success);
            },
            child: const Text('Reject', style: TextStyle(color: Colors.red)),
          ),
        ],
      ),
    );

    reasonController.dispose();
    return result ?? false;
  }

  Future<bool> _showCounterOfferDialog(OfferModel offer) async {
    final result = await showDialog<bool>(
      context: context,
      builder: (context) => CounterOfferDialog(offer: offer),
    );

    return result ?? false;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('My Offers'),
        backgroundColor: const Color(0xFF078893),
        foregroundColor: Colors.white,
        bottom: TabBar(
          controller: _tabController,
          indicatorColor: Colors.white,
          labelColor: Colors.white,
          unselectedLabelColor: Colors.white70,
          tabs: const [
            Tab(text: 'Sent Offers'),
            Tab(text: 'Received Offers'),
          ],
        ),
        actions: [
          IconButton(
            icon: const Icon(LucideIcons.refreshCw),
            onPressed: _refreshOffers,
            tooltip: 'Refresh Offers',
          ),
        ],
      ),
      body: Consumer<OfferProvider>(
        builder: (context, offerProvider, child) {
          return TabBarView(
            controller: _tabController,
            children: [
              // Sent Offers Tab
              _buildOffersTab(
                offers: offerProvider.sentOffers,
                emptyMessage: 'You haven\'t made any offers yet',
                emptyIcon: LucideIcons.send,
                isSentOffers: true,
                isLoading: offerProvider.isLoading,
              ),

              // Received Offers Tab
              _buildOffersTab(
                offers: offerProvider.receivedOffers,
                emptyMessage: 'No offers received yet',
                emptyIcon: LucideIcons.inbox,
                isSentOffers: false,
                isLoading: offerProvider.isLoading,
              ),
            ],
          );
        },
      ),
    );
  }

  Widget _buildOffersTab({
    required List<OfferModel> offers,
    required String emptyMessage,
    required IconData emptyIcon,
    required bool isSentOffers,
    required bool isLoading,
  }) {
    if (isLoading) {
      return const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            CircularProgressIndicator(),
            SizedBox(height: 16),
            Text('Loading offers...'),
          ],
        ),
      );
    }

    if (offers.isEmpty) {
      return RefreshIndicator(
        onRefresh: _refreshOffers,
        child: SingleChildScrollView(
          physics: const AlwaysScrollableScrollPhysics(),
          child: Container(
            height: MediaQuery.of(context).size.height * 0.6,
            child: Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(emptyIcon, size: 64, color: Colors.grey),
                  const SizedBox(height: 16),
                  Text(
                    emptyMessage,
                    style: const TextStyle(fontSize: 18, color: Colors.grey),
                  ),
                  if (isSentOffers) ...[
                    const SizedBox(height: 8),
                    const Text(
                      'Browse products and make offers to get started',
                      style: TextStyle(fontSize: 14, color: Colors.grey),
                    ),
                  ],
                  const SizedBox(height: 16),
                  ElevatedButton.icon(
                    onPressed: _refreshOffers,
                    icon: const Icon(LucideIcons.refreshCw),
                    label: const Text('Refresh'),
                  ),
                ],
              ),
            ),
          ),
        ),
      );
    }

    return RefreshIndicator(
      onRefresh: _refreshOffers,
      child: ListView.builder(
        padding: const EdgeInsets.all(16),
        itemCount: offers.length,
        itemBuilder: (context, index) {
          final offer = offers[index];
          return Padding(
            padding: const EdgeInsets.only(bottom: 12),
            child: OfferCard(
              offer: offer,
              isSentOffer: isSentOffers,
              onAction: (action) => _handleOfferAction(offer, action),
            ),
          );
        },
      ),
    );
  }
}