// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF1ABuqfEC2IJttHVZw2aBPJxxmHCNwT4',
    appId: '1:228460007933:web:1bf442e9aa168ae3ca4994',
    messagingSenderId: '228460007933',
    projectId: 'rebuy-8ef1f',
    authDomain: 'rebuy-8ef1f.firebaseapp.com',
    storageBucket: 'rebuy-8ef1f.firebasestorage.app',
    measurementId: 'G-EKVGKTX9ZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGx-tmLDhLVkmGKy8grtSc1Ia_KVBCve4',
    appId: '1:228460007933:android:b8948ec41970389eca4994',
    messagingSenderId: '228460007933',
    projectId: 'rebuy-8ef1f',
    storageBucket: 'rebuy-8ef1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbMs2t0puDsAj2tcYBthR62mkaM_o74OQ',
    appId: '1:228460007933:ios:a87d274f06aa291eca4994',
    messagingSenderId: '228460007933',
    projectId: 'rebuy-8ef1f',
    storageBucket: 'rebuy-8ef1f.firebasestorage.app',
    iosBundleId: 'com.rebuy.rebuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbMs2t0puDsAj2tcYBthR62mkaM_o74OQ',
    appId: '1:228460007933:ios:a87d274f06aa291eca4994',
    messagingSenderId: '228460007933',
    projectId: 'rebuy-8ef1f',
    storageBucket: 'rebuy-8ef1f.firebasestorage.app',
    iosBundleId: 'com.rebuy.rebuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF1ABuqfEC2IJttHVZw2aBPJxxmHCNwT4',
    appId: '1:228460007933:web:49ecfa80232f4121ca4994',
    messagingSenderId: '228460007933',
    projectId: 'rebuy-8ef1f',
    authDomain: 'rebuy-8ef1f.firebaseapp.com',
    storageBucket: 'rebuy-8ef1f.firebasestorage.app',
    measurementId: 'G-8BH3WV1CYX',
  );
}
